FROM node:22-alpine AS build

ARG AGENT_IMAGEFLOW_VERSION=""
ARG AGENT_IMAGEFLOW_COMMIT=""
ARG AGENT_IMAGEFLOW_BUILD_TIME=""
ARG AGENT_IMAGEFLOW_IMAGE_TAG=""
ENV AGENT_IMAGEFLOW_VERSION=$AGENT_IMAGEFLOW_VERSION
ENV AGENT_IMAGEFLOW_COMMIT=$AGENT_IMAGEFLOW_COMMIT
ENV AGENT_IMAGEFLOW_BUILD_TIME=$AGENT_IMAGEFLOW_BUILD_TIME
ENV AGENT_IMAGEFLOW_IMAGE_TAG=$AGENT_IMAGEFLOW_IMAGE_TAG

WORKDIR /src

COPY web/package.json web/package-lock.json ./web/
RUN npm --prefix web ci

COPY web ./web
RUN npm --prefix web run build

FROM nginx:1.27-alpine

COPY docker/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/web/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
